export const COUNTRIES_REQUEST_START = 'COUNTRIES_REQUEST_LOADING';
export const COUNTRIES_REQUEST_DONE = 'COUNTRIES_REQUEST_DONE';
export const COUNTRIES_REQUEST_ERROR = 'COUNTRIES_REQUEST_ERROR';
export const CITIES_REQUEST_START = 'CITIES_REQUEST_LOADING';
export const CITIES_REQUEST_DONE = 'CITIES_REQUEST_DONE';
export const CITIES_REQUEST_ERROR = 'CITIES_REQUEST_ERROR';
